spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password: sa
    driver-class-name: org.h2.Driver  # database

  jpa:
    hibernate:
      ddl-auto: none    # 자동으로 테이블 만들어주는
    properties:       # 설정 - 스프링부트(사이트) 매뉴얼에 다 있다.
      hibernate:
#        show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug       # hibernate sql에 대한 debug로그들
  org.hibernate.type: trace     # 쿼리 파라미터가 ?인 애들의 어떤 파라미터가 들어갔는지 트레이스를 보여줌  -> 더 정보가 필요하면 외부라이브러리